// Lightweight PDF generation without jsPDF (no CDN access)
// Generates a print-friendly HTML page and triggers browser print
export const printReport = (html, title = "ExamPortal Report") => {
  const w = window.open("", "_blank");
  w.document.write(`<!DOCTYPE html><html><head>
    <title>${title}</title>
    <style>
      * { box-sizing: border-box; margin: 0; padding: 0; }
      body { font-family: 'Segoe UI', sans-serif; color: #1a2332; padding: 40px; }
      .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid #00E5FF; padding-bottom: 16px; margin-bottom: 24px; }
      .logo { font-size: 22px; font-weight: 800; color: #00E5FF; }
      .meta { font-size: 12px; color: #5a7090; }
      h2 { font-size: 18px; margin-bottom: 12px; color: #1a2332; }
      table { width: 100%; border-collapse: collapse; margin-bottom: 24px; font-size: 13px; }
      th { background: #0D1117; color: #00E5FF; padding: 10px 12px; text-align: left; }
      td { padding: 9px 12px; border-bottom: 1px solid #DDE3EC; }
      tr:nth-child(even) td { background: #F0F4F8; }
      .pass { color: #059669; font-weight: 600; }
      .fail { color: #DC2626; font-weight: 600; }
      .stat-grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 24px; }
      .stat-box { background: #F0F4F8; border-radius: 8px; padding: 16px; text-align: center; }
      .stat-val { font-size: 24px; font-weight: 800; color: #00E5FF; }
      .stat-lbl { font-size: 11px; color: #5a7090; margin-top: 4px; }
      .footer { border-top: 1px solid #DDE3EC; padding-top: 12px; font-size: 11px; color: #5a7090; text-align: center; margin-top: 32px; }
      @media print { body { padding: 20px; } }
    </style>
  </head><body>${html}
  <div class="footer">Generated by ExamPortal — ${new Date().toLocaleString()}</div>
  <script>window.onload=()=>{ window.print(); }<\/script>
  </body></html>`);
  w.document.close();
};

export const buildResultReport = (result, exam, student) => {
  const passed = result.passed;
  const qRows = result.answers.map((a, i) => `
    <tr>
      <td>${i + 1}</td>
      <td>${a.question}</td>
      <td>${a.selected ? `Option ${a.selected}` : "Not answered"}</td>
      <td>Option ${a.correct}</td>
      <td>${a.isCorrect ? '<span class="pass">✓ Correct</span>' : a.selected ? '<span class="fail">✗ Wrong</span>' : '<span style="color:#5a7090">— Skipped</span>'}</td>
    </tr>`).join("");

  return `
    <div class="header">
      <div class="logo">EP ExamPortal</div>
      <div class="meta">Report generated: ${new Date().toLocaleString()}</div>
    </div>
    <h2>Exam Result Report</h2>
    <div class="stat-grid">
      <div class="stat-box"><div class="stat-val">${student.name}</div><div class="stat-lbl">Student</div></div>
      <div class="stat-box"><div class="stat-val">${exam.title.split(" ").slice(0,2).join(" ")}</div><div class="stat-lbl">Exam</div></div>
      <div class="stat-box"><div class="stat-val">${result.score}/${result.maxScore}</div><div class="stat-lbl">Score</div></div>
      <div class="stat-box"><div class="stat-val ${passed ? "pass" : "fail"}">${passed ? "PASS" : "FAIL"}</div><div class="stat-lbl">Result (${result.percentage}%)</div></div>
    </div>
    <h2>Question-by-Question Review</h2>
    <table><thead><tr><th>#</th><th>Question</th><th>Your Answer</th><th>Correct</th><th>Result</th></tr></thead>
    <tbody>${qRows}</tbody></table>`;
};

export const buildAdminReport = (stats, studentRows, examRows) => `
  <div class="header">
    <div class="logo">EP ExamPortal</div>
    <div class="meta">Admin Report — ${new Date().toLocaleString()}</div>
  </div>
  <div class="stat-grid">
    <div class="stat-box"><div class="stat-val">${stats.students}</div><div class="stat-lbl">Total Students</div></div>
    <div class="stat-box"><div class="stat-val">${stats.exams}</div><div class="stat-lbl">Total Exams</div></div>
    <div class="stat-box"><div class="stat-val">${stats.attempts}</div><div class="stat-lbl">Total Attempts</div></div>
    <div class="stat-box"><div class="stat-val">${stats.avgScore}%</div><div class="stat-lbl">Avg Score</div></div>
  </div>
  <h2>Student Performance</h2>
  <table><thead><tr><th>Student</th><th>Username</th><th>Exam</th><th>Score</th><th>%</th><th>Status</th></tr></thead>
  <tbody>${studentRows}</tbody></table>
  <h2>Exam Analytics</h2>
  <table><thead><tr><th>Exam</th><th>Attempts</th><th>Avg Score</th><th>Highest</th><th>Lowest</th><th>Pass %</th></tr></thead>
  <tbody>${examRows}</tbody></table>`;
